### ISSUE TITLE
Handle Type Errors

### ISSUE THREAD

**Issue by sgpthomas** [dijkstracula/solvent#1]
At the moment, the only type error handling that we do is to throw an error if unification fails. It would be nice to figure out now to localize a unification error to an actual expression and report a line number / useful message.

We should also figure out what to do if refinement type inference fails. At the moment, I don't think it ever fails, it simply infers True as the refinement if it can't find anything better. I wonder if there is a way to use the counter-examples that z3 generates to report something more useful?

**Comment by dijkstracula** [comment]
> At the moment, I don't think it ever fails, it simply infers True as the refinement if it can't
> find anything better.

This is kind of an interesting observation, and I wonder whether it's better to "fail open" (e.g. just propagate `True` up if PA filters out all qualifiers) or "fail closed" (e.g. "I can't put a qualifier to what you've given me, so I'm going to bail out").  In a setting where it's trivial for the application programmer to add qualifiers or annotate a refinement type manually (e.g. respond with "ok, fine, here's the missing logical fragment you needed; go hog wild"), failing closed certainly has a certain safety logic to it.  By contrast, I wonder if in larger program contexts, if we infer, say, `{int | True}` and actually needed something stronger later on in the program, we'd Floyd-Hoare our way to a contradiction/type error anyway. 

> I wonder if there is a way to use the counter-examples that z3 generates to report 
> something more useful?

I think this is absolutely a cool thing to start exploring - even if it's not used to reject a program that it can't figure refinements out about, using that counterexample and propagating it back to the user, Dafny-style, through an LSP or something, could actually be pretty neat.

Might also be worth looking at how [F*](https://www.fstar-lang.org/tutorial/proof-oriented-programming-in-fstar.pdf) does error reporting, too.
